version: "3"
services:
  jupyterlab:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - $PWD:/content
    working_dir: /content
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.iopub_data_rate_limit=1.0e10
